export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as Services } from './Services/Services';
export { default as Contact } from './Contact/Contact';
export { default as Register } from './Session_Forms/Register';
export { default as Auth } from './Session_Forms/Login_form';
export { default as Navibar } from './Navibar/Navibar';
export { default as Jumbo } from './Home/Jumbo';
export { default as Footer } from './Footer/Footer';